# Generated by Django 4.0.6 on 2022-08-07 13:08

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('question', models.TextField(default='')),
                ('question_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcq_flag', models.BooleanField(default=True)),
                ('marks', models.IntegerField(validators=[quiz.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=20)),
                ('quiz_date_time', models.DateTimeField()),
                ('quiz_duration', models.TimeField()),
                ('quiz_window', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.course')),
            ],
        ),
        migrations.CreateModel(
            name='mcq_question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('option1', models.TextField(default='')),
                ('option2', models.TextField(default='')),
                ('option3', models.TextField(default='')),
                ('option4', models.TextField(default='')),
                ('answer', models.IntegerField()),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='subjective_question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('answer', models.TextField(default='')),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='quiz_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('attempted', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(through='quiz.quiz_grade', to='users.student'),
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grades.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question_bank'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
