# Generated by Django 4.0.6 on 2022-08-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='', max_length=15)),
                ('course_name', models.CharField(max_length=60)),
                ('course_info', models.TextField()),
                ('in_progress', models.BooleanField(default=True)),
                ('past', models.BooleanField(default=False)),
                ('future', models.BooleanField(default=False)),
                ('course_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_students',
            field=models.ManyToManyField(through='grades.grades', to='users.student'),
        ),
    ]
